// ============================================================
// Archetype Test — question bank & values list
// Every scored item is tagged with module, dimension, direction
// (+1 keyed towards the dimension / right-hand pole, -1 reverse-keyed),
// response format, and time window, so scoring is purely mechanical.
// ============================================================

const FREQ = ['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always'];

const EMOTIONS = [
  { k: 'anger',   label: 'Anger / irritation',          ex: 'heat in the chest, "are you serious?", wanting to push back or snap' },
  { k: 'sadness', label: 'Sadness / hurt',              ex: 'a sinking feeling, throat tightens, wanting to withdraw or cry' },
  { k: 'fear',    label: 'Fear / anxiety',              ex: 'stomach drops, mind races to what this means and what happens next' },
  { k: 'shame',   label: 'Shame / guilt',               ex: 'face goes hot, "I\'m an idiot", wanting to disappear' },
  { k: 'numb',    label: 'Numb / detached',             ex: 'flat, not much of anything, watching it from a distance' },
  { k: 'solve',   label: 'Straight to problem-solving', ex: '"okay — what do I do about this", already listing options' },
];

const LANGS = [
  { k: 'words', label: 'Words of affirmation' },
  { k: 'acts',  label: 'Acts of service' },
  { k: 'gifts', label: 'Gifts' },
  { k: 'time',  label: 'Quality time' },
  { k: 'touch', label: 'Physical touch' },
  { k: 'play',  label: 'Shared play / activity' },
];

const DRIVES = [
  { k: 'security',    label: 'Security & certainty',     fear: 'being unprepared, exposed, or unsafe' },
  { k: 'competence',  label: 'Competence & achievement', fear: 'being seen as incapable' },
  { k: 'autonomy',    label: 'Autonomy & control',       fear: 'being controlled or dependent' },
  { k: 'connection',  label: 'Connection & belonging',   fear: 'being unwanted or left out' },
  { k: 'stimulation', label: 'Stimulation & novelty',    fear: 'being trapped in boredom or pain' },
  { k: 'meaning',     label: 'Meaning & being good',     fear: 'being wrong, corrupt, or pointless' },
];

// helper: frequency item
const f = (dim, dir, text, ex) => ({ type: 'freq', dim, dir, text, ex });

const MODULES = [
  // ------------------------------------------------------------
  {
    id: 'state',
    title: 'Before we start',
    short: 'State check',
    intro: 'Three quick questions about how you are <em>right now</em>. These aren\'t scored — they\'re stored with your result so that if you retake the test later, you can see whether a changed score was really you or just the day you were having.',
    items: [
      { type: 'scale', dim: 'stress', text: 'Right now, how stressed do you feel?', lo: 'Not at all', hi: 'Extremely' },
      { type: 'scale', dim: 'sleep',  text: 'How well did you sleep last night?',   lo: 'Terribly',   hi: 'Very well' },
      { type: 'scale', dim: 'mood',   text: 'How is your mood right now?',          lo: 'Very low',   hi: 'Very good' },
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'm1',
    title: 'Temperament',
    short: 'Temperament',
    window: 'Over the past year…',
    intro: 'How you get energy, what you pay attention to, how you decide, and how you like things structured. Each is measured as a <em>spectrum</em>, not a letter — and each also gets a <em>rigidity</em> score: can you do the opposite when the situation calls for it? A strong preference you can flex is different from one you can\'t.',
    dims: {
      energy:    { poles: ['Recharges alone', 'Recharges with people'] },
      attention: { poles: ['Concrete & present', 'Patterns & possibilities'] },
      decision:  { poles: ['Logic & consistency', 'Impact on people'] },
      structure: { poles: ['Closure & plans', 'Open & adaptive'] },
    },
    items: [
      // energy (+ = people)
      f('energy', +1, 'After a long day, I want to be around other people rather than on my own.',
        'finish a long day and text someone "pub?" instead of heading home to the sofa'),
      f('energy', -1, 'A weekend with no social plans feels like a relief.',
        'see an empty Saturday and Sunday in your calendar and feel your shoulders drop'),
      f('energy', +1, 'I talk things through with someone before I know what I think.',
        'ring a friend to think out loud before you\'ve decided anything'),
      f('energy', -1, 'In a group, I find myself waiting for a chance to leave.',
        'sit at a table of six and clock the exit, working out the earliest polite moment to go'),
      f('energy', +1, 'I get restless when I\'ve spent a whole day without seeing anyone.',
        'hit 6pm on a day alone and start pacing, checking your phone for someone to see'),
      f('energy', -1, 'I need a day alone to recover after a big social event.',
        'block out the day after a wedding or party to see nobody'),
      f('energy', +1, 'I say yes to spontaneous invitations even when I\'d planned a quiet night.',
        'get a "we\'re out, come" text at 9pm and go, even though you\'d planned a bath and an early night'),
      f('energy', -1, 'I let calls go to voicemail because I don\'t have the energy to talk.',
        'watch a friend\'s name ring on your phone and let it go because you can\'t face talking'),
      f('energy_rig', -1, 'When I\'m drained, I still manage to show up and be present at things that matter to people I love.',
        'turn up to a friend\'s birthday and actually engage, even though you\'re running on empty'),
      f('energy_rig', +1, 'I\'ve turned down something I actually wanted to do because it needed the "other" mode — too social, or too solitary.',
        'skip a trip you genuinely wanted because it meant a week of constant company (or a week alone)'),
      f('energy_rig', +1, 'People close to me have said I\'m hard to shift once I\'m in my alone-mode or my social-mode.',
        'hear "once you\'ve gone into your cave there\'s no getting you out" (or "once you\'re out, you never go home")'),
      // attention (+ = patterns)
      f('attention', +1, 'When someone explains something, I jump ahead to what it could mean or lead to.',
        'hear the first half of someone\'s idea and are already three steps ahead, thinking about where it leads'),
      f('attention', -1, 'I notice small physical details in a room — what\'s changed, what\'s out of place.',
        'walk into a friend\'s flat and spot the new lamp before they mention it'),
      f('attention', +1, 'I lose track of the present because I\'m thinking about what could be.',
        'miss your stop because you were somewhere in next year'),
      f('attention', -1, 'I prefer instructions that tell me exactly what to do, step by step.',
        'reach for the numbered instructions rather than working the flat-pack out from the picture'),
      f('attention', +1, 'I find myself connecting unrelated ideas from different areas of my life.',
        'catch yourself linking something from a podcast to a problem at work to a thing your mum said'),
      f('attention', -1, 'I trust what I\'ve seen work before more than a promising new idea.',
        'take the route you know over the "faster" one the app suggests'),
      f('attention', +1, 'I get bored by tasks that are pure execution with nothing to figure out.',
        'stall on data entry or filing because there\'s nothing in it to solve'),
      f('attention', -1, 'When I plan something, I think in specifics — times, places, amounts — rather than the overall vision.',
        'plan a holiday by starting with flight times and a budget, not the vibe'),
      f('attention_rig', -1, 'When a situation needs the other mode (hard facts vs. big picture), I can switch without much friction.',
        'drop into hard facts mid-brainstorm (or step back to the big picture mid-checklist) without it feeling like a wrench'),
      f('attention_rig', +1, 'I\'ve missed something important because I was in "my" mode — lost in the big picture, or stuck in the details.',
        'miss a deadline in the small print because you were on the vision (or miss the point of a project because you were in the details)'),
      f('attention_rig', +1, 'I\'ve been told I overthink the meaning of things, or that I miss the point by focusing on specifics.',
        'hear "you\'re reading too much into it" or "you\'re missing the forest for the trees"'),
      // decision (+ = people)
      f('decision', +1, 'When deciding, I ask myself how each person involved will feel about it.',
        'run through how each person at the table will take it before you say what you\'ve decided'),
      f('decision', -1, 'I\'ll say the true thing even if it stings, because being accurate matters more than being gentle.',
        'tell a friend their business plan doesn\'t add up, straight, rather than cushioning it'),
      f('decision', +1, 'I soften feedback so the other person doesn\'t feel bad.',
        'open with two compliments before mentioning the thing that\'s actually wrong'),
      f('decision', -1, 'I get frustrated when people bring emotions into a decision that should be about the facts.',
        'sit in a meeting thinking "this isn\'t about how anyone feels — look at the numbers"'),
      f('decision', +1, 'I\'ve changed a decision because someone was upset by it, even though the original reasoning was sound.',
        'reverse a call you knew was right because someone\'s face fell'),
      f('decision', -1, 'I judge whether something is fair by whether the same rule was applied to everyone.',
        'check "would this be allowed for anyone else?" before you accept an exception'),
      f('decision', +1, 'I find it hard to enforce a rule when I can see it\'s hurting someone in front of me.',
        'let the late fee slide because the person in front of you is visibly struggling'),
      f('decision', -1, 'I\'d rather be right than liked.',
        'hold your position in an argument knowing it\'s costing you goodwill in the room'),
      f('decision_rig', -1, 'When the situation calls for the other approach — warmer, or colder and clearer — I can do it.',
        'switch to warmth when someone\'s fragile, or to cold clarity when someone\'s spiralling — whichever isn\'t your default'),
      f('decision_rig', +1, 'My way of deciding has cost me — a relationship or a good outcome — because I couldn\'t switch.',
        'lose a friendship to bluntness, or lose a good outcome to not wanting to upset anyone'),
      f('decision_rig', +1, 'People have described me as "too soft" or "too cold" in how I make calls.',
        'hear "you\'re a pushover" or "you\'re a robot" about a decision you made'),
      // structure (+ = open)
      f('structure', +1, 'I keep options open until the last possible moment.',
        'leave the "are you coming Saturday?" text unanswered until Saturday'),
      f('structure', -1, 'I feel uneasy until a plan is locked in.',
        'can\'t relax about a trip until flights, hotel and the first dinner are booked'),
      f('structure', +1, 'I start things before I know how they\'ll finish.',
        'start painting the room before you\'ve decided on the colour for the other wall'),
      f('structure', -1, 'I make lists and actually work through them.',
        'write the Sunday list and tick it off by evening'),
      f('structure', +1, 'I change plans on the day because something better came up.',
        'bail on the cinema plan at 5pm because someone mentioned a rooftop'),
      f('structure', -1, 'Unfinished tasks sit in my head until they\'re done.',
        'lie in bed thinking about the email you didn\'t send'),
      f('structure', +1, 'I work best in a burst near a deadline rather than steadily ahead of it.',
        'do the whole thing the night before — and it\'s better for it'),
      f('structure', -1, 'I decide quickly and don\'t reopen decisions once they\'re made.',
        'pick the restaurant in ten seconds and don\'t look at the menu again'),
      f('structure_rig', -1, 'When needed, I can work the other way — improvise when I\'d rather plan, or commit when I\'d rather keep options open.',
        'improvise happily when the plan falls apart, or commit early when the situation needs it — whichever isn\'t your default'),
      f('structure_rig', +1, 'My preferred way of working has caused a real problem — a missed deadline, a missed opportunity, someone let down.',
        'miss a deadline from keeping options open, or miss a good opportunity because it wasn\'t in the plan'),
      f('structure_rig', +1, 'People close to me have complained about how planned, or how last-minute, I am.',
        'hear "can you just decide?" or "can you ever just go with it?"'),
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'm2',
    title: 'Motivation & fear',
    short: 'Motivation',
    window: 'Over the past year…',
    intro: 'What actually drives you — and what you\'re trying to avoid. Six drives are measured <em>independently</em> rather than as a type, so overlaps (like the Enneagram 6/7 blur) show up instead of being hidden. There\'s also a separate question of <em>where you go when you\'re anxious</em>: towards certainty, or towards stimulation.',
    items: [
      f('security', +1, 'I check things more than once — locks, emails, plans — to be sure.',
        'go back to check the front door is locked after you\'ve already checked it'),
      f('security', +1, 'I plan for what could go wrong before I commit to something.',
        'list what could go wrong with the trip before you\'ve said yes to it'),
      f('security', +1, 'I feel calmer when I know exactly what\'s expected of me.',
        'relax the moment someone gives you a clear brief'),
      f('security', -1, 'I\'m comfortable making a big decision with only some of the information.',
        'sign the lease having seen the flat once and skimmed the contract'),
      f('security', +1, 'I look for someone I trust to confirm I\'m doing the right thing.',
        'message a friend "does this sound right?" before you send the email'),
      f('competence', +1, 'I set myself a target and feel off if I don\'t hit it.',
        'feel a low hum of failure all evening because you did four of the five things'),
      f('competence', +1, 'I compare how I\'m doing to how others are doing.',
        'check what stage a peer is at and measure yourself against it'),
      f('competence', +1, 'Being seen as bad at something is worse for me than the thing itself going badly.',
        'care more that people saw you fumble the presentation than that the presentation went badly'),
      f('competence', -1, 'I\'m happy to be average at things that don\'t matter to me.',
        'cheerfully lose at pub quiz or five-a-side without it bothering you'),
      f('competence', +1, 'I keep working on something past the point where it was already good enough.',
        'redo a slide that was fine at 11pm because it could be slightly better'),
      f('autonomy', +1, 'I push back when someone tells me how to do something, even if their way is fine.',
        'do it your way after someone\'s shown you theirs, even though theirs worked'),
      f('autonomy', +1, 'I\'d rather do a job myself than depend on someone else to do it.',
        'do the job first so you don\'t have to rely on anyone — or quietly redo it after they\'ve done it'),
      f('autonomy', +1, 'Being told what to do makes me want to do the opposite.',
        'feel the urge to not do the thing the moment someone says "you should…"'),
      f('autonomy', -1, 'I\'m comfortable handing over control of something that matters to me.',
        'let someone else plan the whole trip and genuinely not check the bookings'),
      f('autonomy', +1, 'I keep parts of my life private so nobody has a say in them.',
        'keep the new project or the new person to yourself so nobody can weigh in'),
      f('connection', +1, 'I notice quickly when someone\'s warmth towards me cools.',
        'notice a friend\'s replies got shorter and feel it within a day'),
      f('connection', +1, 'I adjust what I say so people will like me.',
        'agree with an opinion you don\'t hold to keep the mood warm'),
      f('connection', +1, 'Being left out of something bothers me even when I didn\'t want to go.',
        'see photos of a night you\'d have declined anyway and still feel the sting'),
      f('connection', -1, 'I\'m fine being on the outside of a group.',
        'sit on the edge of a group chat, rarely included, and honestly not mind'),
      f('connection', +1, 'I do things for people mainly so they\'ll want me around.',
        'offer to help with the move partly because it keeps you in the circle'),
      f('stimulation', +1, 'I get bored with routines and change them for the sake of it.',
        'change the gym, the route, or the breakfast just because it\'s been the same for a month'),
      f('stimulation', +1, 'I say yes to new experiences before thinking through whether they\'re a good idea.',
        'say yes to the trip or the tattoo before checking dates or cost'),
      f('stimulation', +1, 'I have several projects or interests going at once.',
        'have three half-started things on the go — a course, a hobby, a side project'),
      f('stimulation', -1, 'I\'m content doing the same thing every weekend.',
        'do the same Saturday — same café, same walk — and feel fully content'),
      f('stimulation', +1, 'When life is calm for a while, I start looking for something to shake it up.',
        'book something, start something or change something when a few quiet weeks go by'),
      f('meaning', +1, 'I feel a pull to do the right thing even when nobody would know otherwise.',
        'go back into the shop to pay for the thing they forgot to charge you for'),
      f('meaning', +1, 'I judge myself harshly when I fall short of my own standards.',
        'replay a small unkindness for days afterwards'),
      f('meaning', +1, 'I need what I do to matter beyond myself.',
        'feel hollow after a week of work that was fine but pointless'),
      f('meaning', -1, 'I\'m not bothered by doing work that has no larger point, as long as it pays.',
        'take the well-paid, meaningless gig without it nagging at you'),
      f('meaning', +1, 'I get angry at things that are unfair even when they don\'t affect me.',
        'get properly worked up about a story where a stranger was treated unfairly'),
      // coping axis: 0 = seek certainty, 100 = seek stimulation
      f('coping', -1, 'When I\'m anxious, I make a plan or a list.',
        'open Notes and start listing steps the moment the anxiety hits'),
      f('coping', +1, 'When I\'m anxious, I distract myself with something fun or new.',
        'put something on, go out, start something — anything but sit with it'),
      f('coping', -1, 'When I\'m anxious, I seek reassurance from someone I trust.',
        'text "is it going to be okay?" to the same person'),
      f('coping', +1, 'When I\'m anxious, I book something to look forward to.',
        'book a trip or tickets within the hour of feeling anxious'),
      f('coping', -1, 'When I\'m anxious, I research the problem until I feel I understand it.',
        'read fourteen articles about the thing until you feel you\'ve got a handle on it'),
      f('coping', +1, 'When I\'m anxious, I keep busy so I don\'t have to sit with it.',
        'clean the flat, answer every email, go for a run — anything but stillness'),
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'm3',
    title: 'Emotional default',
    short: 'Emotion',
    intro: 'What happens in you in the first ten seconds when something bad happens — and what\'s underneath it ten minutes later. Then: whether it goes outward or inward, how fast it arrives, how long it stays, and whether anyone can tell.',
    items: [
      { type: 'pick2', dim: 'first', text: 'You get unexpected, blunt criticism from someone whose opinion you care about.', options: EMOTIONS, tag: 'crit' },
      { type: 'pick2', dim: 'first', text: 'A plan you were really looking forward to falls through at the last minute.', options: EMOTIONS },
      { type: 'pick2', dim: 'first', text: 'Someone you rely on lets you down when it counts.', options: EMOTIONS, tag: 'letdown' },
      { type: 'pick2', dim: 'first', text: 'You get bad news about money or health.', options: EMOTIONS },
      { type: 'pick2', dim: 'first', text: 'You message someone and they leave you on read for days.', options: EMOTIONS, tag: 'ignored' },
      { type: 'pick2', dim: 'first', text: 'You\'re proven wrong in front of people.', options: EMOTIONS },
      { type: 'pick2', dim: 'first', text: 'Someone treats you unfairly — takes credit, cuts in, blames you.', options: EMOTIONS, tag: 'unfair' },
      { type: 'pick2', dim: 'first', text: 'You watch someone else being treated unfairly.', options: EMOTIONS },

      { type: 'pick1', dim: 'second', text: 'The blunt criticism again. <strong>Ten minutes later</strong>, what\'s the feeling underneath?', options: EMOTIONS.concat([{ k: 'same', label: 'The same feeling, still', ex: 'the first feeling hasn\'t shifted or given way to anything else' }]) },
      { type: 'pick1', dim: 'second', text: 'Being let down by someone you rely on. <strong>Ten minutes later</strong>, what\'s underneath?', options: EMOTIONS.concat([{ k: 'same', label: 'The same feeling, still', ex: 'the first feeling hasn\'t shifted or given way to anything else' }]) },
      { type: 'pick1', dim: 'second', text: 'Being left on read for days. <strong>Ten minutes after you noticed</strong>, what\'s underneath?', options: EMOTIONS.concat([{ k: 'same', label: 'The same feeling, still', ex: 'the first feeling hasn\'t shifted or given way to anything else' }]) },
      { type: 'pick1', dim: 'second', text: 'Being treated unfairly. <strong>Ten minutes later</strong>, what\'s underneath?', options: EMOTIONS.concat([{ k: 'same', label: 'The same feeling, still', ex: 'the first feeling hasn\'t shifted or given way to anything else' }]) },

      // direction: 0 inward, 100 outward
      f('direction', +1, 'When something goes wrong, my first thought is who caused it.',
        'think "who did this?" before "what happened?"'),
      f('direction', -1, 'When something goes wrong, my first thought is what I did wrong.',
        'think "what did I miss?" before anything else'),
      f('direction', +1, 'I let people know when they\'ve upset me.',
        'say "that annoyed me" to their face rather than sitting on it'),
      f('direction', -1, 'I replay my own mistakes far more than other people\'s.',
        'still think about your slip-up from Tuesday while theirs is long forgotten'),
      f('direction', +1, 'I raise my voice or get sharp when I\'m upset.',
        'hear your own voice go up, or your words get clipped, when you\'re upset'),
      // speed: higher = fast
      f('speed', +1, 'I go from calm to upset in seconds.',
        'feel it flip in seconds — one comment and you\'re there'),
      f('speed', -1, 'It takes a while for something to actually get to me.',
        'only realise you\'re upset about it hours later, in the shower'),
      f('speed', +1, 'People are surprised by how quickly my mood turns.',
        'hear "where did that come from?" after a fast mood change'),
      f('speed', +1, 'I react on the spot rather than later.',
        'respond in the moment rather than coming back to it the next day'),
      // recovery: higher = slow
      f('recovery', +1, 'I\'m still upset about something the next day.',
        'wake up still carrying yesterday\'s argument'),
      f('recovery', -1, 'Once I\'ve had it out, I\'m over it within the hour.',
        'have the row, and be laughing with them an hour later'),
      f('recovery', +1, 'A bad moment in the morning colours my whole day.',
        'let one bad email at 9am sit on the whole day'),
      f('recovery', -1, 'I can be genuinely fine again soon after being upset.',
        'feel it fully, then genuinely be fine twenty minutes later'),
      // expression: higher = shows
      f('expression', +1, 'People can tell from my face when I\'m upset.',
        'get asked "what\'s wrong?" before you\'ve said anything'),
      f('expression', -1, 'I keep a neutral front when I\'m upset.',
        'keep a straight face while furious inside, and nobody knows'),
      f('expression', +1, 'I say out loud what I\'m feeling, as I\'m feeling it.',
        'say "I\'m mad right now" out loud while you\'re still feeling it'),
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'm4',
    title: 'Conflict, grievance & repair',
    short: 'Conflict',
    window: 'Over the past year…',
    intro: 'Do you address things immediately or keep a mental ledger — and if you keep one, what happens to it? Plus how long grudges last, how comfortable you are confronting people, and who reaches out first after a fight.',
    items: [
      // timing: 0 immediate, 100 bank it
      f('timing', -1, 'When someone close to me does something that bothers me, I tell them within a day or two.',
        'mention "that thing yesterday bothered me" by the next day'),
      f('timing', +1, 'I let small things slide and keep a note of them.',
        'say nothing about the comment, but file it'),
      f('timing', -1, 'I bring up an issue while it\'s still happening rather than afterwards.',
        'say "hang on, that\'s not okay" in the moment'),
      f('timing', +1, 'I can list things a person did months ago that I never raised.',
        'could, right now, list three things a friend did in spring that you never mentioned'),
      f('timing', +1, 'I\'ve told someone "it\'s fine" when it wasn\'t.',
        'say "it\'s fine, honestly" while it is very much not fine'),
      f('timing', -1, 'I\'d rather have an awkward conversation now than resent someone later.',
        'choose the uncomfortable chat this week over a quiet grudge next month'),
      // ledger type
      { type: 'choice', dim: 'ledger', text: 'A friend forgets something important to you. You don\'t mention it at the time. Weeks later…', opts: [
        { k: 'cashin',   text: 'It comes out during an unrelated argument.' },
        { k: 'withdraw', text: 'I\'ve quietly become a bit less available to them.' },
        { k: 'letgo',    text: 'I\'ve genuinely forgotten about it.' },
        { k: 'resent',   text: 'I\'m still friendly, but I think about it when I see them.' },
      ]},
      { type: 'choice', dim: 'ledger', text: 'A partner or housemate keeps leaving a shared task to you…', opts: [
        { k: 'cashin',   text: 'One day I bring up everything at once.' },
        { k: 'withdraw', text: 'I stop doing things for them, without saying why.' },
        { k: 'letgo',    text: 'I let it go — it\'s not worth it.' },
        { k: 'resent',   text: 'I do the task and feel quietly resentful every time.' },
      ]},
      { type: 'choice', dim: 'ledger', text: 'Someone makes a joke at your expense in front of others…', opts: [
        { k: 'cashin',   text: 'I bring it up later, when I\'m already annoyed at them about something else.' },
        { k: 'withdraw', text: 'I\'m cooler with them for a while.' },
        { k: 'letgo',    text: 'I laugh it off and it\'s gone.' },
        { k: 'resent',   text: 'I laugh at the time, but it stays with me.' },
      ]},
      { type: 'choice', dim: 'ledger', text: 'A colleague takes credit for your idea…', opts: [
        { k: 'cashin',   text: 'I keep it in reserve for when I need leverage.' },
        { k: 'withdraw', text: 'I stop sharing ideas with them.' },
        { k: 'letgo',    text: 'I mention it once, then it\'s done.' },
        { k: 'resent',   text: 'I say nothing, but rate them lower from then on.' },
      ]},
      { type: 'choice', dim: 'ledger', text: 'A family member says something dismissive about your choices…', opts: [
        { k: 'cashin',   text: 'It resurfaces at the next family argument.' },
        { k: 'withdraw', text: 'I visit or call less.' },
        { k: 'letgo',    text: 'I let it pass — they\'re like that.' },
        { k: 'resent',   text: 'I\'m polite, but I keep a running tally.' },
      ]},
      { type: 'choice', dim: 'ledger', text: 'Think of the person who has wronged you most. Today…', opts: [
        { k: 'cashin',   text: 'I\'d raise it if we ever argued again.' },
        { k: 'withdraw', text: 'I\'ve distanced myself without explaining.' },
        { k: 'letgo',    text: 'I\'ve made peace with it.' },
        { k: 'resent',   text: 'I\'m civil, but it\'s never far from my mind.' },
      ]},

      // grudge: higher = long half-life
      f('grudge', +1, 'Once someone has hurt me, I don\'t fully trust them again.',
        'stay friends after a betrayal but never quite hand over the same trust'),
      f('grudge', -1, 'I can forgive someone and actually mean it.',
        'forgive someone and find you genuinely don\'t think about it anymore'),
      f('grudge', +1, 'I remember exactly what people said in arguments years ago.',
        'could quote what they said in that argument in 2021'),
      f('grudge', -1, 'I\'m able to be warm again with someone shortly after they\'ve hurt me.',
        'be properly warm with someone within a day of them hurting you'),
      // assertiveness: higher = comfortable confronting
      f('assert', +1, 'I\'m comfortable telling someone directly that they\'ve crossed a line.',
        'say "that\'s not okay with me" to someone\'s face without rehearsing'),
      f('assert', -1, 'I rehearse difficult conversations many times and often don\'t have them.',
        'script the conversation in the shower for a week and then never have it'),
      f('assert', +1, 'I can disagree with someone senior to me, to their face.',
        'tell your boss "I don\'t think that\'s right" in the meeting, not afterwards'),
      f('assert', -1, 'I avoid conflict even when it costs me.',
        'let the wrong order, the unfair split, the overcharge go, because raising it feels worse'),
      // repair: higher = initiates
      f('repair', +1, 'After a fight, I\'m the one who reaches out first.',
        'send the first "can we talk?" after a row'),
      f('repair', -1, 'I wait for the other person to apologise before I\'ll talk.',
        'stay silent until they say sorry, however long that takes'),
      f('repair', +1, 'I can say "I was wrong" without it feeling like defeat.',
        'say "you were right, I was wrong" and mean it, without it stinging much'),
      f('repair', -1, 'I go silent after a fight and let it fade rather than resolve it.',
        'let a fight go quiet and drift back to normal without ever talking about it'),
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'bounds',
    title: 'Boundaries',
    short: 'Boundaries',
    window: 'Over the past year…',
    intro: 'Three separate things that get lumped together as "having boundaries". <em>Setting</em> — do you say the limit at all? <em>Holding</em> — once said, does it survive being pushed? And <em>cost</em> — when you give way, does it actually take something from you, or was it genuinely not that deep? Giving way a lot isn\'t a problem by itself. Giving way a lot <em>and</em> paying for it is.',
    items: [
      // setting: higher = says the limit; lower = goes along
      f('setting', +1, 'I say no to things I don\'t want to do, without a long excuse.',
        'reply "no, I can\'t this week" and leave it there'),
      f('setting', -1, 'I say yes to a request while already knowing I\'ll resent it.',
        'agree to cover a shift and feel the resentment land before you\'ve even hung up'),
      f('setting', +1, 'I tell people what I need from them, even when it\'s awkward.',
        'say "I need you to text if you\'re going to be late" instead of quietly stewing'),
      f('setting', -1, 'I go along with a plan I don\'t like rather than say so.',
        'end up at the restaurant you didn\'t want because you said "anything\'s fine"'),
      f('setting', -1, 'I let people take more of my time, money, or energy than I\'d decided to give.',
        'lend the "last time" for the third time'),
      f('setting', +1, 'I\'ve let someone know a limit before they crossed it, not just after.',
        'say "I\'ll need to leave by ten" at the start of the night, not at half eleven when you\'re stuck'),
      f('setting', -1, 'People find out what my limits are only once I\'ve been pushed past them.',
        'blow up over something small because it was the tenth small thing, and nobody knew about the other nine'),
      // holding: higher = holds under pushback; lower = folds
      f('holding', -1, 'I\'ve said no, been asked again, and said yes.',
        'hold out through "are you sure?" and cave at "please, just this once"'),
      f('holding', +1, 'When someone pushes back on a limit I\'ve set, I hold it.',
        'repeat "I can\'t, sorry" the second time, calmly, without a new excuse'),
      f('holding', -1, 'I set a boundary and then quietly stop enforcing it.',
        'say "no calls after ten" and be answering them again within a fortnight'),
      f('holding', -1, 'If someone seems hurt or annoyed by my no, I take it back.',
        'see their face fall and hear yourself saying "actually, it\'s fine, I\'ll do it"'),
      f('holding', +1, 'I can sit with someone being disappointed in me without fixing it.',
        'let the silence after your "no" stay there instead of filling it with an offer'),
      f('holding', -1, 'I come up with a fresh excuse each time I\'m asked, rather than just repeating no.',
        'go from "I\'m busy" to "I\'m not feeling well" to "maybe next week" for the same request'),
      // cost: higher = giving way is costing you; lower = it genuinely doesn't
      f('cost', +1, 'After giving way to someone, I feel resentful rather than fine.',
        'drive home from the favour muttering about it'),
      f('cost', +1, 'The same few people keep asking me for things I\'ve regretted saying yes to.',
        'know exactly who\'s going to text next time they need a lift, a loan, a favour'),
      f('cost', +1, 'Looking back over the past few months, I can see I\'ve consistently put my own needs last.',
        'realise you haven\'t done the thing you actually wanted on a single weekend since the semester started'),
      f('cost', -1, 'When I go along with something, I genuinely don\'t mind — it isn\'t costing me anything.',
        'eat at their pick of restaurant and be truly fine with it, not "fine"'),
      f('cost', +1, 'I\'ve been tired, broke, or behind because of things I agreed to for other people.',
        'miss your own deadline because you spent the weekend helping with theirs'),
      f('cost', +1, 'I feel taken for granted.',
        'notice nobody asks any more, they just assume'),
      // why you gave way: fine / ease / fear / owed
      { type: 'choice', dim: 'why', text: 'A friend asks a favour on a day you\'d set aside for yourself. You do it. Most likely because…', opts: [
        { k: 'fine', text: 'It genuinely didn\'t matter to me — I was happy to.' },
        { k: 'ease', text: 'Pushing back felt like more effort than it was worth.' },
        { k: 'fear', text: 'I worried about how they\'d feel about me if I said no.' },
        { k: 'owed', text: 'I felt I owed it, or had no right to say no.' } ]},
      { type: 'choice', dim: 'why', text: 'Someone keeps talking well past the time you said you needed to go. You stay. Because…', opts: [
        { k: 'fine', text: 'I didn\'t actually mind — the plan could wait.' },
        { k: 'ease', text: 'Cutting them off felt like more hassle than staying.' },
        { k: 'fear', text: 'Leaving felt like it would come across as rude or cold.' },
        { k: 'owed', text: 'They needed it, so my plans didn\'t count.' } ]},
      { type: 'choice', dim: 'why', text: 'A family member pushes you on a decision that\'s yours to make, and you go with their version. Because…', opts: [
        { k: 'fine', text: 'I didn\'t feel strongly — either way was fine.' },
        { k: 'ease', text: 'Arguing wasn\'t worth the energy.' },
        { k: 'fear', text: 'I didn\'t want the disapproval that comes with going against them.' },
        { k: 'owed', text: 'After everything they\'ve done, it felt wrong to push back.' } ]},
      { type: 'choice', dim: 'why', text: 'A bill gets split in a way that leaves you paying more than your share. You say nothing. Because…', opts: [
        { k: 'fine', text: 'It was a few dollars — genuinely not that deep.' },
        { k: 'ease', text: 'Raising it would have been awkward for everyone.' },
        { k: 'fear', text: 'I didn\'t want to look petty or tight.' },
        { k: 'owed', text: 'I probably owed them from some other time anyway.' } ]},
      { type: 'choice', dim: 'why', text: 'Someone asks a personal question you\'d rather not answer. You answer it. Because…', opts: [
        { k: 'fine', text: 'On reflection it wasn\'t that private.' },
        { k: 'ease', text: 'Deflecting would have been more awkward than answering.' },
        { k: 'fear', text: 'Refusing felt like it would make things weird between us.' },
        { k: 'owed', text: 'They\'d shared with me, so I felt I had to.' } ]},
      { type: 'choice', dim: 'why', text: 'A group-project partner or colleague hands you their part of the work. You do it. Because…', opts: [
        { k: 'fine', text: 'I was going to do it better anyway, and didn\'t mind.' },
        { k: 'ease', text: 'Chasing them would have taken longer than just doing it.' },
        { k: 'fear', text: 'I didn\'t want to be the difficult one.' },
        { k: 'owed', text: 'They\'ve got more on than me — it felt fair.' } ]},
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'm5',
    title: 'Attachment & closeness',
    short: 'Attachment',
    window: 'In your closest relationships, over the past year…',
    intro: 'Two continuous axes — <em>anxiety</em> (worry about being left, need for reassurance) and <em>avoidance</em> (discomfort with closeness and depending on people) — plus how each shifts when you\'re under stress, because that\'s when attachment actually shows.',
    items: [
      f('anxiety', +1, 'I worry that people I care about will lose interest in me.',
        'wonder whether a close friend is starting to drift away'),
      f('anxiety', +1, 'I need reassurance that I matter to the people close to me.',
        'feel the need to hear "you matter to me" said out loud'),
      f('anxiety', +1, 'I read a lot into a short reply or a changed tone.',
        'get "ok." instead of "ok!" and spend the afternoon on it'),
      f('anxiety', -1, 'I\'m relaxed when someone I\'m close to is busy and not in touch.',
        'go a week without hearing from your best friend and not think twice'),
      f('anxiety', +1, 'I worry I care about people more than they care about me.',
        'suspect you\'re the one keeping the friendship going'),
      f('anxiety', +1, 'When someone pulls away a little, I pull closer.',
        'send a second, warmer message when the first one got a cool reply'),
      f('anxiety', -1, 'I can go days without contact from a partner or close friend and feel fine.',
        'go three days without a message from your partner and feel completely fine'),
      f('anxiety', +1, 'I feel a bit panicked when a relationship seems uncertain.',
        'feel a flutter of panic when a friendship or relationship feels unsteady'),
      f('avoidance', +1, 'I find it hard to depend on other people.',
        'struggle to ask for a lift, a loan, or a favour, even from close friends'),
      f('avoidance', +1, 'I keep some distance even in my closest relationships.',
        'hold something back even with the person who knows you best'),
      f('avoidance', -1, 'I\'m comfortable sharing what I\'m really feeling with someone close.',
        'say "actually, I\'m struggling" to someone close without much friction'),
      f('avoidance', +1, 'When someone wants to get closer, I feel a pull to back off.',
        'feel the urge to cancel when someone\'s getting keen'),
      f('avoidance', +1, 'I\'d rather deal with a problem alone than lean on someone.',
        'handle a bad week entirely alone rather than tell anyone'),
      f('avoidance', -1, 'I open up easily to people I trust.',
        'tell a trusted friend the real thing within minutes of them asking'),
      f('avoidance', +1, 'Being needed by someone feels heavy.',
        'feel a weight, not a warmth, when someone says they need you'),
      f('avoidance', -1, 'I\'m comfortable relying on a partner or close friend when things are hard.',
        'let someone take over when things are hard, and feel relief rather than unease'),
      f('anx_stress', +1, 'When I\'m stressed, I want more contact and reassurance than usual.',
        'text more, call more, and want to hear "we\'re okay" when you\'re stressed'),
      f('anx_stress', +1, 'Under stress, I worry more that people are annoyed with me.',
        'assume a colleague\'s short reply means they\'re annoyed at you, on a stressful week'),
      f('anx_stress', +1, 'Under stress, my mind goes to whether the relationship is okay.',
        'find your thoughts drifting to "are we okay?" when the stress is actually about work'),
      f('av_stress',  +1, 'When I\'m stressed, I want to be left alone.',
        'say "I just need space" when things pile up'),
      f('av_stress',  +1, 'Under stress, I get irritated by people trying to help.',
        'snap "I\'m fine" at someone who\'s only trying to help'),
      f('av_stress',  +1, 'Under stress, I shut down rather than talk.',
        'go quiet for days rather than say what\'s going on'),
    ],
  },

  // ------------------------------------------------------------
  {
    id: 'm6',
    title: 'Love languages, split',
    short: 'Love languages',
    intro: 'Two separate rankings. <strong>Expressive</strong> — what you actually <em>do</em> for people you care about (easy to recall). <strong>Receptive</strong> — what would <em>land</em> for you, asked as hypotheticals so you don\'t need memories of having received it. A sixth language, <em>shared play</em>, is included because many people find it distinct from quality time.',
    items: [
      // expressive: frequency, "for people I care about"
      f('give_words', +1, 'I tell people what I appreciate about them, specifically.',
        'say "I love how you always notice when someone\'s left out" — the specific thing, not just "you\'re great"'),
      f('give_acts',  +1, 'I do a chore or errand for someone without being asked.',
        'take the bins out, pick up their parcel, or fill their car without being asked'),
      f('give_gifts', +1, 'I buy or make something for someone because it reminded me of them.',
        'see a mug, a book, or a plant and buy it because it\'s so them'),
      f('give_time',  +1, 'I clear my schedule to spend unhurried time with someone.',
        'cancel something so you can spend a whole afternoon with them, no rush'),
      f('give_touch', +1, 'I hug, touch an arm, or sit close to people I\'m comfortable with.',
        'hug hello, touch an arm mid-story, sit close on the sofa'),
      f('give_play',  +1, 'I invite people to do an activity together — a game, sport, cooking, a trip.',
        'send "climbing Saturday?" or "come cook with me"'),
      f('give_words', +1, 'I send messages just to say I\'m thinking of someone.',
        'send "thinking of you", or a photo that reminded you of them, apropos of nothing'),
      f('give_acts',  +1, 'I fix or sort something out for someone because I noticed it needed doing.',
        'fix their wobbly shelf or sort out their phone settings because you noticed'),
      f('give_gifts', +1, 'I put real thought into gifts rather than getting something generic.',
        'plan a birthday present weeks ahead so it lands exactly'),
      f('give_time',  +1, 'I put my phone away and give someone my full attention.',
        'put your phone face down and in your bag for the whole dinner'),
      f('give_touch', +1, 'I reach for physical contact to comfort someone.',
        'put a hand on their back or pull them into a hug when they\'re upset'),
      f('give_play',  +1, 'I show I care by planning something fun for us to do.',
        'book the escape room, the day trip, the game night — as your way of saying you care'),
      f('give_words', +1, 'I compliment people out loud when I notice something good.',
        'say "that was a great call" or "you look really well" the moment you notice'),
      f('give_acts',  +1, 'I show up to help when someone\'s moving, sick, or overwhelmed.',
        'turn up with boxes, soup, or a spare pair of hands'),
      f('give_gifts', +1, 'I bring something back for people when I\'ve been away.',
        'come back from a trip with a small thing for two or three people'),
      f('give_time',  +1, 'I\'d rather spend an evening with one person than at a gathering.',
        'pick a long dinner for two over the big night out'),
      f('give_touch', +1, 'I\'m physically affectionate with partners.',
        'reach for their hand, lean in, stay in contact when you\'re together'),
      f('give_play',  +1, 'I bond with people by doing things side by side rather than by talking.',
        'feel closest when you\'re cooking, building, or playing something together, not in deep chat'),
      // receptive: forced-choice pairs (every language vs every other = 15)
      { type: 'choice', dim: 'recv', text: 'You\'re exhausted after a hard week. Which would land more?', opts: [
        { k: 'words', text: 'Someone tells you how proud they are of how you handled it.' },
        { k: 'acts',  text: 'Someone quietly does your laundry and cooks dinner.' } ]},
      { type: 'choice', dim: 'recv', text: 'It\'s your birthday.', opts: [
        { k: 'words', text: 'A long handwritten letter about what you mean to them.' },
        { k: 'gifts', text: 'A gift they clearly hunted for that\'s exactly your taste.' } ]},
      { type: 'choice', dim: 'recv', text: 'Which stays with you longer?', opts: [
        { k: 'words', text: 'A heartfelt message saying they love you.' },
        { k: 'time',  text: 'A whole afternoon together, no plan, no phones.' } ]},
      { type: 'choice', dim: 'recv', text: 'You\'ve had bad news.', opts: [
        { k: 'words', text: 'Someone says exactly the right thing.' },
        { k: 'touch', text: 'Someone says nothing and holds you.' } ]},
      { type: 'choice', dim: 'recv', text: 'Which would you replay later?', opts: [
        { k: 'words', text: 'A friend tells you you\'re one of their favourite people.' },
        { k: 'play',  text: 'A friend books you both onto something they know you\'d love doing.' } ]},
      { type: 'choice', dim: 'recv', text: 'You\'re moving house.', opts: [
        { k: 'acts',  text: 'A friend shows up and packs boxes all day.' },
        { k: 'gifts', text: 'A friend sends a thoughtful housewarming gift.' } ]},
      { type: 'choice', dim: 'recv', text: 'Which means more?', opts: [
        { k: 'acts', text: 'Your partner handles all the admin you\'ve been dreading.' },
        { k: 'time', text: 'Your partner takes a day off just to be with you.' } ]},
      { type: 'choice', dim: 'recv', text: 'You\'re sick.', opts: [
        { k: 'acts',  text: 'Someone brings soup and sorts out your meds.' },
        { k: 'touch', text: 'Someone sits on the bed and strokes your hair.' } ]},
      { type: 'choice', dim: 'recv', text: 'You\'ve been in a rut.', opts: [
        { k: 'acts', text: 'Someone fixes the thing you\'ve been putting off.' },
        { k: 'play', text: 'Someone drags you out for the day to do something you love.' } ]},
      { type: 'choice', dim: 'recv', text: 'An ordinary Tuesday.', opts: [
        { k: 'gifts', text: 'A small surprise gift, for no reason.' },
        { k: 'time',  text: 'A spontaneous "let\'s go for a walk, just us."' } ]},
      { type: 'choice', dim: 'recv', text: 'They come home…', opts: [
        { k: 'gifts', text: '…with your favourite thing.' },
        { k: 'touch', text: '…and pull you into a long hug.' } ]},
      { type: 'choice', dim: 'recv', text: 'Your hobby.', opts: [
        { k: 'gifts', text: 'They got you something for it.' },
        { k: 'play',  text: 'They joined you in it for the day.' } ]},
      { type: 'choice', dim: 'recv', text: 'End of a good day.', opts: [
        { k: 'time',  text: 'A long, uninterrupted conversation.' },
        { k: 'touch', text: 'Falling asleep close together.' } ]},
      { type: 'choice', dim: 'recv', text: 'A free Saturday with someone you love.', opts: [
        { k: 'time', text: 'Sitting together talking for hours.' },
        { k: 'play', text: 'A day out doing something active together.' } ]},
      { type: 'choice', dim: 'recv', text: 'On the sofa.', opts: [
        { k: 'touch', text: 'Cuddling.' },
        { k: 'play',  text: 'Playing a game together.' } ]},

      // absence items: how much would it hurt if it stopped
      { type: 'absence', dim: 'abs_words', text: 'If a partner or close friend <strong>stopped telling you they appreciate you</strong>…' },
      { type: 'absence', dim: 'abs_acts',  text: 'If they <strong>stopped doing practical things for you</strong>…' },
      { type: 'absence', dim: 'abs_gifts', text: 'If they <strong>stopped bringing you thoughtful things</strong>…' },
      { type: 'absence', dim: 'abs_time',  text: 'If they <strong>stopped making unhurried time for you</strong>…' },
      { type: 'absence', dim: 'abs_touch', text: 'If they <strong>stopped being physically affectionate</strong>…' },
      { type: 'absence', dim: 'abs_play',  text: 'If they <strong>stopped suggesting things to do together</strong>…' },
    ],
  },
];

const ABSENCE_LABELS = ['Wouldn\'t notice', 'Would notice eventually', 'Would notice within weeks', 'Would notice fast, and mind', 'Would hurt a lot'];

// assign stable ids
MODULES.forEach(m => m.items.forEach((it, i) => { it.id = `${m.id}-${String(i + 1).padStart(2, '0')}`; it.module = m.id; }));

// ============================================================
// Values — Russ Harris ACT list plus additions, with one-line definitions.
// src: 'harris' | 'added'. merged: values folded into this one.
// ============================================================
const VALUES = [
  { name: 'Acceptance',      src: 'harris', def: 'Being open to and at peace with myself, others, and life as it is.' },
  { name: 'Adventure',       src: 'harris', def: 'Actively seeking out new, exciting, or unusual experiences.' },
  { name: 'Assertiveness',   src: 'harris', def: 'Standing up for my rights and asking clearly for what I want.' },
  { name: 'Authenticity',    src: 'harris', def: 'Being genuine and real; not performing a version of myself.' },
  { name: 'Beauty',          src: 'harris', def: 'Creating, appreciating, and surrounding myself with beauty.' },
  { name: 'Caring',          src: 'harris', def: 'Looking after myself, others, the environment.' },
  { name: 'Challenge',       src: 'harris', def: 'Pushing myself to grow, learn, and do hard things.' },
  { name: 'Compassion',      src: 'harris', def: 'Responding to suffering — mine or others\' — with kindness.' },
  { name: 'Connection',      src: 'harris', def: 'Being fully present and engaged with the people I\'m with.' },
  { name: 'Contribution',    src: 'harris', def: 'Giving, helping, and making a positive difference.' },
  { name: 'Conformity',      src: 'harris', def: 'Respecting rules, norms, and how things are done.' },
  { name: 'Cooperation',     src: 'harris', def: 'Working well with others towards shared goals.' },
  { name: 'Courage',         src: 'harris', def: 'Acting in the face of fear, threat, or difficulty.' },
  { name: 'Creativity',      src: 'harris', def: 'Making, inventing, and expressing original ideas.' },
  { name: 'Curiosity',       src: 'harris', def: 'Being open-minded and interested; exploring and discovering.' },
  { name: 'Encouragement',   src: 'harris', def: 'Rewarding and supporting behaviour I value in myself and others.' },
  { name: 'Fairness',        src: 'harris', def: 'Treating people equally and justly; playing by the same rules for everyone.', merged: ['Equality'] },
  { name: 'Excitement',      src: 'harris', def: 'Seeking and creating stimulating, thrilling experiences.' },
  { name: 'Fitness',         src: 'harris', def: 'Maintaining and improving my physical health and capability.' },
  { name: 'Flexibility',     src: 'harris', def: 'Adjusting readily to changing circumstances.' },
  { name: 'Freedom',         src: 'harris', def: 'Living how I choose; helping others do the same.' },
  { name: 'Friendliness',    src: 'harris', def: 'Being warm, open, and pleasant towards people.' },
  { name: 'Forgiveness',     src: 'harris', def: 'Letting go of resentment towards myself and others.' },
  { name: 'Fun',             src: 'harris', def: 'Seeking, creating, and engaging in playful, enjoyable activities.' },
  { name: 'Generosity',      src: 'harris', def: 'Giving freely — time, money, attention — to others.' },
  { name: 'Gratitude',       src: 'harris', def: 'Appreciating what I have and what others do for me.' },
  { name: 'Honesty',         src: 'harris', def: 'Being truthful and sincere, even when it costs me.' },
  { name: 'Humour',          src: 'harris', def: 'Seeing and appreciating the funny side of life.' },
  { name: 'Humility',        src: 'harris', def: 'Letting my actions speak; not needing to be the centre.' },
  { name: 'Industry',        src: 'harris', def: 'Being hard-working and dedicated to my work.' },
  { name: 'Independence',    src: 'harris', def: 'Supporting myself and choosing my own path.' },
  { name: 'Intimacy',        src: 'harris', def: 'Opening up and sharing myself deeply with someone.' },
  { name: 'Justice',         src: 'harris', def: 'Upholding what is right; opposing what is wrong.' },
  { name: 'Kindness',        src: 'harris', def: 'Being considerate and warm-hearted towards myself and others.' },
  { name: 'Knowledge',       src: 'harris', def: 'Learning, understanding, and sharing what I know.' },
  { name: 'Love',            src: 'harris', def: 'Acting lovingly and affectionately towards myself and others.' },
  { name: 'Mindfulness',     src: 'harris', def: 'Being present, open, and curious about the here and now.' },
  { name: 'Order',           src: 'harris', def: 'Being organised; keeping things tidy and in their place.' },
  { name: 'Open-mindedness', src: 'harris', def: 'Considering other views and weighing evidence fairly.' },
  { name: 'Patience',        src: 'harris', def: 'Waiting calmly for what I want without forcing it.' },
  { name: 'Persistence',     src: 'harris', def: 'Continuing despite problems, setbacks, or slow progress.' },
  { name: 'Pleasure',        src: 'harris', def: 'Creating and enjoying sensory and bodily enjoyment.' },
  { name: 'Power',           src: 'harris', def: 'Strongly influencing or having authority over people and outcomes.' },
  { name: 'Reciprocity',     src: 'harris', def: 'Building relationships with a fair balance of give and take.' },
  { name: 'Respect',         src: 'harris', def: 'Being considerate and polite; treating people with dignity.' },
  { name: 'Responsibility',  src: 'harris', def: 'Being accountable for my actions and their consequences.' },
  { name: 'Romance',         src: 'harris', def: 'Being passionate and affectionate in love.' },
  { name: 'Safety',          src: 'harris', def: 'Securing and protecting myself and others from harm.' },
  { name: 'Self-awareness',  src: 'harris', def: 'Understanding my own thoughts, feelings, and patterns.' },
  { name: 'Self-care',       src: 'harris', def: 'Looking after my own health and wellbeing.' },
  { name: 'Self-development',src: 'harris', def: 'Continually growing, advancing, and improving.' },
  { name: 'Self-control',    src: 'harris', def: 'Acting in line with my ideals rather than my impulses.' },
  { name: 'Sensuality',      src: 'harris', def: 'Enjoying and exploring the five senses.' },
  { name: 'Sexuality',       src: 'harris', def: 'Exploring and expressing my sexuality.' },
  { name: 'Spirituality',    src: 'harris', def: 'Connecting with something larger than myself.' },
  { name: 'Competence',      src: 'harris', def: 'Being genuinely skilled and capable at what I do.', merged: ['Skilfulness'] },
  { name: 'Supportiveness',  src: 'harris', def: 'Being helpful, encouraging, and available to others.' },
  { name: 'Trust',           src: 'harris', def: 'Being trustworthy — loyal, sincere, reliable — and extending trust.' },

  { name: 'Integrity',       src: 'added',  def: 'My actions match my words and my principles, whether or not anyone is watching.' },
  { name: 'Decorum',         src: 'added',  def: 'Conducting myself with propriety and good manners appropriate to the setting.' },
  { name: 'Loyalty',         src: 'added',  def: 'Standing by the people and commitments I\'ve chosen, especially when it\'s hard.' },
  { name: 'Dignity',         src: 'added',  def: 'Carrying myself with self-respect; not debasing myself or others.' },
  { name: 'Discretion',      src: 'added',  def: 'Keeping confidences; knowing what not to say and when.' },
  { name: 'Ambition',        src: 'added',  def: 'Aiming high and striving to reach it.' },
  { name: 'Tradition',       src: 'added',  def: 'Honouring customs, rituals, and what has been passed down.' },
  { name: 'Excellence',      src: 'added',  def: 'Doing things to a genuinely high standard; craftsmanship.' },
  { name: 'Stability',       src: 'added',  def: 'Having a predictable, steady foundation to life.' },
  { name: 'Wisdom',          src: 'added',  def: 'Seeing clearly, judging well, and knowing what matters.' },
  { name: 'Faith',           src: 'added',  def: 'Trusting in a belief, a path, or a higher power.' },
  { name: 'Family',          src: 'added',  def: 'Prioritising and investing in the people I call family.' },
  { name: 'Legacy',          src: 'added',  def: 'Leaving something behind that outlasts me.' },
  { name: 'Prosperity',      src: 'added',  def: 'Building material security and abundance.' },
  { name: 'Recognition',     src: 'added',  def: 'Being seen and acknowledged for what I do.' },
  { name: 'Reliability',     src: 'added',  def: 'Doing what I said I\'d do, when I said I\'d do it.' },
  { name: 'Resilience',      src: 'added',  def: 'Recovering from setbacks and carrying on.' },
  { name: 'Privacy',         src: 'added',  def: 'Keeping parts of my life my own.' },
  { name: 'Rationality',     src: 'added',  def: 'Reasoning clearly and deciding on logic and evidence rather than impulse or feeling.', merged: ['Logic'] },
  { name: 'Pragmatism',      src: 'added',  def: 'Doing what actually works; practical over ideal.' },
];
VALUES.forEach((v, i) => { v.id = v.name.toLowerCase().replace(/[^a-z]+/g, '-'); });

// Insight thresholds & archetype naming tables live in scoring.js
